development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: ec2-54-225-121-179.compute-1.amazonaws.com
  database: d2flcpcksu0rfb
  user: wjfmwuqxqvbwnq
  port: 5432
  password: 0LR1RhGf9pOVaf-ZmwUCE5Qufg